package com.cabatuan.displaywebpagedemo;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.webkit.WebView;

public class MainActivity extends AppCompatActivity {


    public void displayWebpage(){
        WebView wv = (WebView) findViewById(R.id.webviewdlsu);
        wv.getSettings().setLoadWithOverviewMode(true);
        wv.getSettings().setUseWideViewPort(true);
        wv.loadUrl("http://www.dlsu.edu.ph");
    }


    /**************************************************************************
     * BELOW THIS POINT IS CODE THAT WAS GENERATED BY ANDROID STUDIO THAT WE  *
     * DID NOT MODIFY, EXCEPT FOR LINE THAT IS MARKED WITH MKC RESPECTIVELY.*
     **************************************************************************/

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        displayWebpage(); // mkc
    }
}